spring:
  application:
    name: CLOUD-GATEWAY      
  cloud:
    gateway:
      routes:
      - id: VISITOR-SERVICE
        uri: http://localhost:9001/
        predicates:
        - Path=/visitors/**
        
        
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost 